### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by pr0nopoly** [pr0stats/pr0stats#1]
Hi,

I want to create queries for myself. Is there any possibility to get the database? Or the script to create an own version of it?

**Comment by dialogik** [comment]
The operator of that page asked us to not publish the code of the script, we respect that. But you can [suggest queries/questions to the data set](https://github.com/pr0stats/pr0stats/issues/new). Take a look [at the database schema](http://pr0stats.github.io/methodik.html) if you want to know about available attributes.

**Comment by dialogik** [comment]
The provider of pr0gramm.com asked us not to publish the script. We offer to use the data for specific purposes. What would you be interested in?
